---
- name: install Docker
  hosts: all
  become: true
  tasks:
    - name: updating apt packages
      shell: "apt-get update"

    - name: upgrading server
      shell: "apt-get upgrade -y"

    - name: Install apt-transport-https
      shell: "apt install ca-certificates curl gnupg lsb-release -y"

    - name: Add signing key
      shell: mkdir -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Add repository into sources list
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    
    - name: updating apt packages
      shell: "apt update"
    
    - name: check if docker exists on server
      shell: "which docker" 
      register: output
      ignore_errors: yes

    - name: Install Docker
      shell: "apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-compose -y"
      when: output.rc == 1

    - name: enabling docker service
      shell: systemctl enable docker.service

    - name: restarting docker service
      shell: systemctl restart docker.service

    - name: adding ubuntu user to docker group
      shell: usermod -aG docker ubuntu